//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace УП
{
    using System;
    using System.Collections.Generic;
    
    public partial class aptekapost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public aptekapost()
        {
            this.aptekasklad = new HashSet<aptekasklad>();
        }
    
        public int Code_post { get; set; }
        public string Short_name { get; set; }
        public string Long_name { get; set; }
        public string adress { get; set; }
        public string phone { get; set; }
        public string FIO_dir { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aptekasklad> aptekasklad { get; set; }
    }
}
