//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace УП
{
    using System;
    using System.Collections.Generic;
    
    public partial class aptekasklad
    {
        public Nullable<int> Code_drug { get; set; }
        public Nullable<int> kod_post { get; set; }
        public Nullable<System.DateTime> data_post { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<int> value_drug { get; set; }
        public int kod_postup { get; set; }
    
        public string retName
        {
            get
            {
                return apteka.Name_drug;
            }
        }
        public string retpost
        {
            get
            {
                return aptekapost.Long_name;
            }
        }
        public virtual apteka apteka { get; set; }
        public virtual aptekapost aptekapost { get; set; }
    }
}
