//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace УП
{
    using System;
    using System.Collections.Generic;
    
    public partial class apteka
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public apteka()
        {
            this.aptekasklad = new HashSet<aptekasklad>();
        }
    
        public int Code_drug { get; set; }
        public string Name_drug { get; set; }
        public string use_drug { get; set; }
        public string EI { get; set; }
        public Nullable<int> value_in_pack { get; set; }
        public string Name_maker { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aptekasklad> aptekasklad { get; set; }
    }
}
